// AUTO-GENERATED by scripts/export-abis.mjs — do not edit.
import CharterFactoryAbi from "./abis/CharterFactory.json";
import BankAbi from "./abis/Bank.json";
import PolicyRegistryAbi from "./abis/PolicyRegistry.json";
import ExecutionRouterAbi from "./abis/ExecutionRouter.json";
import PrivacyPoolAbi from "./abis/PrivacyPool.json";
import MockUSDCAbi from "./abis/MockUSDC.json";
import MockYieldVaultAbi from "./abis/MockYieldVault.json";

export const abis = {
  CharterFactory: CharterFactoryAbi,
  Bank: BankAbi,
  PolicyRegistry: PolicyRegistryAbi,
  ExecutionRouter: ExecutionRouterAbi,
  PrivacyPool: PrivacyPoolAbi,
  MockUSDC: MockUSDCAbi,
  MockYieldVault: MockYieldVaultAbi,
} as const;
