// AUTO-GENERATED by scripts/export-abis.mjs — do not edit.
import CharterFactoryAbi from "./abis/CharterFactory.json";
import BankAbi from "./abis/Bank.json";
import PolicyRegistryAbi from "./abis/PolicyRegistry.json";
import ExecutionRouterAbi from "./abis/ExecutionRouter.json";
import MockUSDCAbi from "./abis/MockUSDC.json";
import MockYieldVaultAbi from "./abis/MockYieldVault.json";

export const abis = {
  CharterFactory: CharterFactoryAbi as const,
  Bank: BankAbi as const,
  PolicyRegistry: PolicyRegistryAbi as const,
  ExecutionRouter: ExecutionRouterAbi as const,
  MockUSDC: MockUSDCAbi as const,
  MockYieldVault: MockYieldVaultAbi as const,
};
