#!/usr/bin/env node
// Extract ABIs from forge build output into packages/shared/src/abis/*.json
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "packages/contracts/out");
const dest = join(root, "packages/shared/src/abis");
mkdirSync(dest, { recursive: true });

const contracts = [
  "CharterFactory",
  "Bank",
  "PolicyRegistry",
  "ExecutionRouter",
  "MockUSDC",
  "MockYieldVault",
];

const index = {};
for (const c of contracts) {
  const p = join(out, `${c}.sol`, `${c}.json`);
  if (!existsSync(p)) {
    console.warn(`! missing artifact for ${c} (run forge build first)`);
    continue;
  }
  const artifact = JSON.parse(readFileSync(p, "utf8"));
  writeFileSync(join(dest, `${c}.json`), JSON.stringify(artifact.abi, null, 2));
  index[c] = artifact.abi;
  console.log(`exported ${c} ABI (${artifact.abi.length} entries)`);
}

// Combined TS module for easy typed import.
const ts =
  `// AUTO-GENERATED by scripts/export-abis.mjs — do not edit.\n` +
  contracts
    .map((c) => `import ${c}Abi from "./abis/${c}.json";`)
    .join("\n") +
  `\n\nexport const abis = {\n` +
  contracts.map((c) => `  ${c}: ${c}Abi as const,`).join("\n") +
  `\n};\n`;
writeFileSync(join(root, "packages/shared/src/abis.ts"), ts);
console.log("wrote packages/shared/src/abis.ts");
